insert into user (username, password, role) values ('John', 'john123', 'SALE');
insert into user (username, password, role) values ('Susan', 'susan123', 'WAREHOUSE');
insert into user (username, password, role) values ('sales', 'asdffdsa', 'SALE');
insert into user (username, password, role) values ('warehouse', 'asdffdsa', 'WAREHOUSE');



insert into region (name) values ('YGN');

insert into township (name) values ('Kyauktada');
insert into township (name) values ('Bahan');
insert into township (name) values ('Kamaryut');
insert into township (name) values ('Mingalar Taung Nyunt');
insert into township (name) values ('Sanchaung');
insert into township (name) values ('Lanmadaw');
insert into township (name) values ('Pabedan');
insert into township (name) values ('Tamwe');
insert into township (name) values ('Yankin');
insert into township (name) values ('Ahlone');

insert into shop (name, region_id, township_id, address, available_status) values ('Tech Nest', 1, 10, 'No-155, Lower Kyi Myin Dine Road', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Digital Hub', 1, 2, 'No-45, Kabar Aye Pagoda Road', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Cyber Core', 1, 7, 'Junction City Mall, Level 3', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Code & Pixel', 1, 6, 'No-85, Landamadaw Street', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Byte Bazaar', 1, 5, 'No-56, Pyay Road', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('NextGen Gadgets', 1, 2, 'Myanmar Plaza, Level 1', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Infinity Tech Store', 1, 1, 'No-102, Sule Pagoda Road', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('GigaWorld Electronics', 1, 5, 'Dagon Center II', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Circuit City Pro', 1, 4, 'Yuzana Plaza', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('The Data Den', 1, 1, 'No-15, Pansodan Street', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Innovate IT', 1, 5, 'No-29, Myaynigone Zay Street', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('PC Planet', 1, 7, 'No-44, Seikanthar Street', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Future Bytes', 1, 8, 'Ocean Supercenter', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('SmartEdge Solutions', 1, 3, 'No-60, University Avenue Road', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Cloud Connectors', 1, 2, 'Pearl Condo', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Mega Tech Mart', 1, 4, 'Mingalar Market', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Hardware Haven', 1, 6, 'Junction Mawtin, Level 2', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('IT Essentials Co.', 1, 9, 'Yankin Center', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Tech Fusion Store', 1, 1, 'No-78, 35th Street', 'OPEN');
insert into shop (name, region_id, township_id, address, available_status) values ('Binary Boutique', 1, 1, 'No-18, Bogalay Zay Street ', 'OPEN');

insert into brand (name) values ('Apple');
insert into brand (name) values ('Microsoft');
insert into brand (name) values ('G Skill');
insert into brand (name) values ('Itel');
insert into brand (name) values ('HP');
insert into brand (name) values ('LG');
insert into brand (name) values ('WD');
insert into brand (name) values ('Epson');
insert into brand (name) values ('Logitech');
insert into brand (name) values ('Samsung');
insert into brand (name) values ('Canon');
insert into brand (name) values ('APC');
insert into brand (name) values ('Dell');
insert into brand (name) values ('Asus');
insert into brand (name) values ('Seagate');
insert into brand (name) values ('Cisco');
insert into brand (name) values ('TP-link');
insert into brand (name) values ('Acer');
insert into brand (name) values ('HyperX');
insert into brand (name) values ('MSI');

insert into category (name) values ('Storage Device');
insert into category (name) values ('Printer');
insert into category (name) values ('Accessories');
insert into category (name) values ('Power Supply');
insert into category (name) values ('Desktop');
insert into category (name) values ('Laptop');
insert into category (name) values ('Networking Device');
insert into category (name) values ('Memory');
insert into category (name) values ('Software');

insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values (CURRENT_DATE, 1, '7149', 'CONSUMER', 7, "black", 'PENDING');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values (CURRENT_DATE, 1, '7148', 'CONSUMER', 7, "white", 'PENDING');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values (CURRENT_DATE, 1, '7147', 'CONSUMER', 4, "black", 'PENDING');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values (CURRENT_DATE, 1, '7146', 'CONSUMER', 10, "black", 'COMPLETED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values (CURRENT_DATE, 1, '7145', 'CONSUMER', 4, "black", 'PENDING');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values (CURRENT_DATE, 1, '7144', 'CONSUMER', 15, "white", 'COMPLETED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-10', 1, '7143', 'CONSUMER', 11, "gray", 'PENDING');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-10', 1, '7142', 'CONSUMER', 8, "black", 'COMPLETED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-10', 1, '7141', 'CONSUMER', 16, "red", 'COMPLETED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-09', 1, '7140', 'CONSUMER', 20, "black", 'DELIVERING');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-09', 1, '7139', 'CONSUMER', 18, "black", 'DELIVERING');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-09', 1, '7138', 'CONSUMER', 3, "yellow", 'DELIVERING');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-09', 1, '7137', 'CONSUMER', 5, "black", 'CANCELED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-08', 1, '7136', 'CONSUMER', 8, "green", 'DELIVERED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-08', 1, '7135', 'CONSUMER', 12, "black", 'DELIVERED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-07', 1, '7134', 'CONSUMER', 19, "gray", 'DELIVERED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-07', 1, '7133', 'CONSUMER', 17, "green", 'DELIVERED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-07', 1, '7132', 'CONSUMER', 13, "black", 'CANCELED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-07', 1, '7131', 'CONSUMER', 11, "white", 'DELIVERED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-06', 1, '7130', 'CONSUMER', 10, "black", 'DELIVERED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-06', 1, '7129', 'CONSUMER', 14, "white", 'COMPLETED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-05', 1, '7128', 'CONSUMER', 9, "black", 'COMPLETED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-04', 1, '7127', 'CONSUMER', 7, "gray", 'COMPLETED');
insert into orders (created_date, created_user_id, invoice_no, product_segment, shop_id, remarks, status) values ('2025-02-04', 1, '7126', 'CONSUMER', 2, "black", 'DELIVERED');

insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Dell XPS 13', 13, 6, 'DELL-XPS-13', 0, 1800000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Lenovo IdeaPad 5', 4, 6, 'LENOVO-IDEA-5112', 0, 800000, 0, 30);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('HP EliteBook 840', 2, 6, 'HP840-G8-12AB34CD56', 0, 2000000, 0, 10);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Asus TUF Gaming F15 ', 12, 1, 'ASUS-F15-TUF12345GH', 0, 700000, 0, 5);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Acer Aspire 5 ', 5, 9, 'ACER-A515-X123YZ4567', 0, 600000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Apple MacBook Pro 14-inch', 9, 5, 'APPLE-MACPRO-14INC', 0, 650000, 0, 35);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('MSI Prestige 14', 4, 7, 'MSI-PRES14-123', 0, 3000000, 0, 46);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('HP Omen 25L', 6, 6, 'HP-OMEN25L-123XYZ4567', 0, 1500000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Dell OptiPlex 7090', 8, 8, 'DELL-OPT7090-1234', 0, 1300000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Asus ROG Strix G10', 17, 3, 'ASUS-ROG1-G10', 0, 600000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Microsoft Surface Studio', 18, 2, 'MICRO-SUF1-STUD1', 0, 500000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('ViewSonic VX3276 Monitor', 19, 4, 'VIEWSON-VX3276-1024', 0, 400000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('LG UltraGear 27-inch', 20, 3, 'LGUG-27GP950-ABC12345D', 0, 6500000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Samsaung Smart Monitor M8', 10, 1, 'SAMSASUNG-SMARTM8-1024', 0, 4500000, 0, 7);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Dell XPS 15', 7, 2, 'DELL-XPS-15', 0, 10000000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Logitech MX Keys Keyboard', 6, 7, 'LOGITECH-MXKE-1234', 0, 1600000, 0, 26);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Razer Basilisk V3 Mouse ', 5, 6, 'RAZER-BASIV3-MOU', 0, 1400000, 0, 21);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Kingston NV2 2TB SSD', 4, 3, 'KINGSTON-NV2TB-SSD', 0, 1100000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('WD Black SN850X 1TB SSD', 3, 4, 'WBBLACK-SN850X-1TBSD', 0, 1700000, 0, 17);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Seagate IronWolf 4TB HDD', 2, 4, 'SEA-IW4TB-1234GHIJK', 0, 900000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Samsung T7 Protabel SSD', 4, 1, 'SAMSUNG-T7PRO-SSD', 0, 2500000, 0, 9);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('TP-link Deco XE75 Router', 1, 7, 'TP-DECO-XE75', 0, 2000000, 0, 10);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Cisco Catalyst 9200 Switch', 6, 6, 'CISCO-CATS-9200', 0, 450000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Epson EcoTank ET-3850', 15, 3, 'EPS-ET3850-QWERT12345', 0, 650000, 0, 18);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Canon Image CLASS MF644 CDW', 16, 7, 'CAN-MF644CDW-PQR12345', 0, 700000, 0, 15);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Adobe Photoshop CC', 17, 9, 'ADOBE-PHOTO-CC', 0, 6000000, 0, 14);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Microsoft Office 2021', 20, 6, 'MICROSOFT-OFFICE-2021', 0, 7000000, 0, 13);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('Kaspersky Total Security', 13, 5, 'KASPER-SKY-SE123', 0, 1400000, 0, 10);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('NVIDIA RTZ 4060 GPU', 11, 8, 'NVIDIA-RTX-4060', 0, 1800000, 0, 20);
insert into product (name, brand_id, category_id, serial_number, stock_faulty, price, cashback, stock) values ('G.Skill Trident Z RAM 32 GB', 14, 6, 'GSKILL-TRI-Z32GB', 0, 1800000, 0, 8);

insert into service_center (name, contact, address, available_status) values ('Access Spectrum Co., Ltd', '+951-376448 ', '364-366, Maha Bandoola Garden Street, Kyauktada Township, Yangon', 'OPEN');
insert into service_center (name, contact, address, available_status) values ('COMPUTER TECHNICAL TEAM (Trading) Co., Ltd', '+951-8398792', 'No. 11/13, 45th Street, Botahtaung Township, Yangon', 'OPEN');
insert into service_center (name, contact, address, available_status) values ('Myanma Computer Company', '+951-245762', 'Theingyi Bazaar, Block C, 3rd Floor, Ward 3&4, Pabedan Township, Yangon', 'OPEN');
insert into service_center (name, contact, address, available_status) values ('ICT Com', '+959-977715152', '1st Floor, Room 5, Sein Gay Har Super Center, Pabedan Township, Yangon', 'OPEN');
insert into service_center (name, contact, address, available_status) values ('Lenovo Exclusive Store', '+951-9253636', 'Junction City, Bogyoke Road, Pabedan Township, Yangon', 'OPEN');
insert into service_center (name, contact, address, available_status) values ('Myanmar ICT Park', '+951-652236', 'Hlaing Campus, Yangon', 'OPEN');
insert into service_center (name, contact, address, available_status) values ('ASUS Myanmar Service Center', '+959-79345678', '2nd Floor, Ocean Supercenter, Kamayut Township, Yangon', 'OPEN');
insert into service_center (name, contact, address, available_status) values ('HP Authorized Service Center', '+951-558855', 'Pearl Condo Tower A, Bahan Township, Yangon', 'OPEN');
insert into service_center (name, contact, address, available_status) values ('Dell Service Center', '+951-556677', 'Pyay Road, Sanchaung Township, Yangon', 'OPEN');
insert into service_center (name, contact, address, available_status) values ('Zawgyi Electronics  goods and ICT product repairs', '+951-394095', 'Anawrahta Road, Downtown Yangon', 'OPEN');


insert into driver (driver_name, contact, vehicle_plate_no) VALUES ('Ko Tun Lin', '09313485321', 'YGN-1A/3456');
insert into driver (driver_name, contact, vehicle_plate_no) VALUES ('Ko Min Thant', '09399485321', 'MDY-4B/7890');
insert into driver (driver_name, contact, vehicle_plate_no) VALUES ('Ko Hla Oo', '09432485321', 'BGO-6D/4852');
insert into driver (driver_name, contact, vehicle_plate_no) VALUES ('Ko Soe Aung', '0987485321', 'NPT-2C/1789');

INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 1, 5, 'early bird', 75000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (12, 13, 10, 'bulk order', 120000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 7, 50, 'special request', 202020);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (9, 6, 25, 'loyalty customer', 404400);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 13, 15, 'urgent', 168066);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (13, 5, 7, 'staff discount', 8684);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (10, 13, 16, 'clearance', 1779056);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 9, 18, 'repeat order', 190368);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (9, 19, 30, 'new customer', 180270);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (8, 8, 24, 'first purchase', 720000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (15, 18, 9, 'gift order', 135000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 25, 42, 'international', 210000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 2, 10, 'seasonal sale', 150000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (8, 22, 36, 'pre-order', 540000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (4, 3, 5, 'backorder', 22500);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (3, 1, 4, 'express delivery', 100000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (1, 10, 23, 'sample order', 345000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (11, 15, 19, 'promotional', 760000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 13, 26, 'subscription', 390000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (16, 30, 31, 'bulk order', 465000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 10, 30, 'clearance', 450000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (2, 7, 38, 'urgent', 380000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 4, 21, 'seasonal sale', 315000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 11, 12, 'express delivery', 180000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (19, 28, 13, 'international', 195000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 13, 3, 'sample order', 45000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (10, 26, 19, 'loyalty customer', 285000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (20, 12, 18, 'repeat order', 270000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 15, 25, 'pre-order', 375000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (17, 29, 5, 'first purchase', 75000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (5, 13, 35, 'gift order', 525000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (16, 17, 5, 'backorder', 75000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (6, 9, 14, 'staff discount', 210000);
INSERT INTO product_order (order_id, product_id, qty, remark, sub_total) VALUES (12, 9, 7, 'new customer', 105000);
